version: "3.8"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - APP_KEY=b75f1ac3ac0d4bffa4b48f0d2ecebfef
      - APP_PORT=1337
      - DATABASE_URI=root:Secret123@tcp(db)/pretest?parseTime=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
  db:
    restart: unless-stopped
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=pretest
      - MYSQL_ROOT_PASSWORD=Secret123
    networks:
      - net
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pSecret123" ]
      timeout: 20s
      retries: 10
networks:
  net:
    driver: bridge

volumes:
  dbdata: